services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./secrets:/run/secrets
    entrypoint: ["/tools/entrypoint.sh"]
    restart: always
    ports:
      - 3306:3306
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wp_data:/srv/www
    depends_on: 
      - mariadb
    restart: always
    ports:
      - "8080:80"
volumes:
  mariadb_data:
  wp_data:
