services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:v1.0
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    ports:
      - 443:443
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:v1.0
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

  redis:
    container_name: redis
    build: ./requirements/redis
    image: redis:v1.0
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:v1.0
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on: 
      - mariadb
      - redis
    networks:
      - inception
    env_file:
      - .env

  adminer:
    container_name: adminer
    build: ./requirements/adminer
    image: adminer:v1.0
    networks:
      - inception
    depends_on:
      - mariadb
      - nginx
    restart: always

  static_site:
    container_name: static_site
    image: static:v1.0
    build: ./requirements/static_site
    networks:
      - inception
    depends_on:
      - nginx
    ports:
      - "8080:8080"
    restart: always

  portainer:
    container_name: portainer
    build: ./requirements/portainer
    image: portainer:v1.0
    networks:
      - inception
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  ftp:
    container_name: ftp
    build: ./requirements/ftp
    image: ftp:v1.0
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/home/ftpuser
    networks:
      - inception
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always

volumes:
  mariadb_data:
      name: db_data
      driver_opts:
        type: none
        device: /home/nhayoun/data/db
        o: bind

  wordpress_data:
      name: wp_data
      driver_opts:
        type: none
        device: /home/nhayoun/data/wp
        o: bind

  static_site_data:
      name: static_data
      driver_opts:
        type: none
        device: /home/nhayoun/data/static
        o: bind

  portainer_data:
      name: portainer_data
      driver_opts:
        type: none
        device: /home/nhayoun/data/portainer
        o: bind

networks:
  inception: