services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on: 
      - mariadb
    networks:
      - inception
    env_file:
      - ../secrets/wp_credentials

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - ../secrets/wp_credentials

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - inception
    expose:
      - 8080
    depends_on:
      - mariadb
    restart: always
  

volumes:
  mariadb_data:
  wordpress_data:


networks:
  inception: