services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    entrypoint: ["/tools/entrypoint.sh"]
    restart: always
    ports:
      - 3306:3306
    secrets:
      - db_credentials
  # wordpress:
  #   build: ./requirements/wordpress
  #   volumes:
  #     - wp_data:/srv/www
  #   depends_on: 
  #     - mariadb
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   secrets:
  #     - wp_credentials

secrets:
  db_credentials:
    file: ../secrets/db_credentials
  # wp_credentials:
  #   file: ../secrets/wp_credentials
volumes:
  mariadb_data:
  # wp_data: